export const ActivityType = {
  // Project registration
  PROJECT_CREATED: "PROJECT_CREATED",
  PROJECT_UPDATED: "PROJECT_UPDATED",
  PROJECT_REGISTRATION_SUBMITTED: "PROJECT_REGISTRATION_SUBMITTED",
  PROJECT_APPROVED: "PROJECT_APPROVED",
  PROJECT_REJECTED: "PROJECT_REJECTED",
  PROJECT_ASSIGNED: "PROJECT_ASSIGNED",
  PROJECT_UNASSIGNED: "PROJECT_UNASSIGNED",

  // Certification application
  CERT_APP_CREATED: "CERT_APP_CREATED",
  CERT_APP_UPDATED: "CERT_APP_UPDATED",
  CERT_APP_SUBMITTED: "CERT_APP_SUBMITTED",
  CERT_APP_APPROVED: "CERT_APP_APPROVED",
  CERT_APP_REJECTED: "CERT_APP_REJECTED",
  FINAL_SUBMIT: "FINAL_SUBMIT",
  CERT_RESUBMITTED: "CERT_RESUBMITTED",

  // Form data
  FORM_DATA_SAVED: "FORM_DATA_SAVED",

  // Documents
  DOCUMENT_UPLOADED: "DOCUMENT_UPLOADED",
  DOCUMENT_REPLACED: "DOCUMENT_REPLACED",
  DOCUMENT_DELETED: "DOCUMENT_DELETED",
  DOCUMENT_APPROVED: "DOCUMENT_APPROVED",
  DOCUMENT_REJECTED: "DOCUMENT_REJECTED",
  DOCUMENT_REMARKS_ADDED: "DOCUMENT_REMARKS_ADDED",

  // TPA
  TPA_ASSIGNED: "TPA_ASSIGNED",
  TPA_REASSIGNED: "TPA_REASSIGNED",
  TPA_CREDIT_REVIEWED: "TPA_CREDIT_REVIEWED",
  TPA_POINTS_ASSIGNED: "TPA_POINTS_ASSIGNED",
  TPA_POINTS_UPDATED: "TPA_POINTS_UPDATED",
  TPA_POINTS_REMOVED: "TPA_POINTS_REMOVED",
  TPA_REMARKS_ADDED: "TPA_REMARKS_ADDED",
  TPA_REMARKS_UPDATED: "TPA_REMARKS_UPDATED",

  // Staff
  STAFF_ASSIGNED: "STAFF_ASSIGNED",
  STAFF_REASSIGNED: "STAFF_REASSIGNED",
  TEAM_ASSIGNED: "TEAM_ASSIGNED",
  STAFF_CREDIT_REVIEW: "STAFF_CREDIT_REVIEW",
  STAFF_PROJECT_REVIEW: "STAFF_PROJECT_REVIEW",
  STAFF_APPROVAL: "STAFF_APPROVAL",
  STAFF_REJECTION: "STAFF_REJECTION",

  // Admin / user management
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_ACTIVATED: "USER_ACTIVATED",
  USER_DEACTIVATED: "USER_DEACTIVATED",
  PASSWORD_RESET: "PASSWORD_RESET",
  ROLE_CHANGED: "ROLE_CHANGED",

  // Client
  CLIENT_LOGIN: "CLIENT_LOGIN",
  CLIENT_REGISTERED: "CLIENT_REGISTERED",

  CERTIFICATE_ACCEPTED: "CERTIFICATE_ACCEPTED",
  CERTIFICATE_REJECTED: "CERTIFICATE_REJECTED",
  CERTIFICATE_EDITED: "CERTIFICATE_EDITED",
  CERTIFICATE_DOWNLOADED: "CERTIFICATE_DOWNLOADED",

  // Workflow
  WORKFLOW_STATUS_CHANGED: "WORKFLOW_STATUS_CHANGED",
  FINAL_SUBMITTED: "FINAL_SUBMITTED",
} as const;

export type ActivityTypeValue = (typeof ActivityType)[keyof typeof ActivityType];
